# Generated by Django 4.2.3 on 2023-08-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_view_files', 'can view files'), ('candownloadfiles', 'Can download files'), ('can_view_files_scripts', 'can view files and scripts'), ('can_view_database', 'can view database'), ('can_execute_scripts', 'can execute scripts'), ('can_view_files_sftp', 'can view files and sftp'), ('kubernetes', 'can view kubernetes'), ('docker', 'can view docker'), ('jenkins', 'can view jenkins'), ('git', 'can view git'), ('gitlab', 'can view gitlab'), ('ansible', 'can view ansible'), ('terraform', 'can view terraform'), ('grafana', 'can view grafana'), ('prometheus', 'can view prometheus'), ('kibana', 'can view kibana'), ('postgresql', 'can view postgresql'), ('rabbitmq', 'can view rabbitmq'), ('mongodb', 'can view mongodb'), ('elasticsearch', 'can view elasticsearch'), ('redis', 'can view redis'), ('nginx', 'can view nginx')],
            },
        ),
    ]
